const data = [
    {"date": "2024-05-01", "userName": "John Doe", "rating": 4, "score": 85, "comment": "Great service! but can improve especially at the service. I got some problem in my room", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-02", "userName": "Jane Smith", "rating": 4, "score": 78, "comment": "Good, but can improve.", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-05-03", "userName": "Alice Johnson", "rating": 5, "score": 95, "comment": "Excellent!", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-05-04", "userName": "Robert Brown", "rating": 3, "score": 60, "comment": "Not satisfied.", "location": "Houston", "sentiment": "negative"},
    {"date": "2024-05-05", "userName": "Michael Davis", "rating": 4, "score": 82, "comment": "Very good experience.", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-06", "userName": "Emily Wilson", "rating": 4, "score": 84, "comment": "Would recommend!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-05-07", "userName": "Daniel Martinez", "rating": 3, "score": 75, "comment": "Average service.", "location": "Chicago", "sentiment": "negative"},
    {"date": "2024-05-08", "userName": "Sarah Anderson", "rating": 5, "score": 90, "comment": "Loved it!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-05-09", "userName": "David Thomas", "rating": 3, "score": 70, "comment": "Could be better.", "location": "New York", "sentiment": "negative"},
    {"date": "2024-05-10", "userName": "Laura Jackson", "rating": 5, "score": 88, "comment": "Fantastic!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-05-11", "userName": "Mark Wilson", "rating": 4, "score": 83, "comment": "Great experience!", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-05-12", "userName": "Emma Brown", "rating": 3, "score": 72, "comment": "Not bad.", "location": "Houston", "sentiment": "negative"},
    {"date": "2024-05-13", "userName": "James Garcia", "rating": 5, "score": 92, "comment": "Absolutely amazing!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-14", "userName": "Sophia Hernandez", "rating": 4, "score": 80, "comment": "Solid service.", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-05-15", "userName": "Alexander Martinez", "rating": 3, "score": 73, "comment": "Could improve.", "location": "Chicago", "sentiment": "negative"},
    {"date": "2024-05-16", "userName": "Olivia Miller", "rating": 4, "score": 81, "comment": "Impressed!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-05-17", "userName": "William Davis", "rating": 5, "score": 94, "comment": "Top-notch!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-18", "userName": "Isabella Rodriguez", "rating": 3, "score": 76, "comment": "Decent.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-05-19", "userName": "Mason Wilson", "rating": 4, "score": 86, "comment": "Excellent service.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-05-20", "userName": "Ava Garcia", "rating": 4, "score": 87, "comment": "Very satisfied!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-05-21", "userName": "Ethan Hernandez", "rating": 5, "score": 97, "comment": "Outstanding!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-22", "userName": "Charlotte Smith", "rating": 3, "score": 74, "comment": "Average experience.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-05-23", "userName": "Logan Johnson", "rating": 4, "score": 89, "comment": "Great!", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-05-24", "userName": "Amelia Brown", "rating": 5, "score": 93, "comment": "Absolutely fantastic!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-05-25", "userName": "Jacob Garcia", "rating": 4, "score": 82, "comment": "Very good!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-05-26", "userName": "Lily Martinez", "rating": 3, "score": 77, "comment": "Needs improvement.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-05-27", "userName": "Michael Wilson", "rating": 4, "score": 84, "comment": "Solid.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-05-28", "userName": "Sophia Davis", "rating": 5, "score": 95, "comment": "Exceptional!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-05-29", "userName": "Benjamin Rodriguez", "rating": 3, "score": 71, "comment": "Fair.", "location": "New York", "sentiment": "negative"},
    {"date": "2024-05-30", "userName": "Emily Wilson", "rating": 4, "score": 88, "comment": "Would recommend!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-05-31", "userName": "William Anderson", "rating": 4, "score": 86, "comment": "Excellent service.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-01", "userName": "Olivia Thomas", "rating": 5, "score": 98, "comment": "Absolutely fantastic!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-02", "userName": "James Wilson", "rating": 3, "score": 79, "comment": "Satisfactory.", "location": "New York", "sentiment": "negative"},
    {"date": "2024-06-03", "userName": "Sophia Johnson", "rating": 4, "score": 85, "comment": "Very pleased.", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-06-04", "userName": "Ethan Brown", "rating": 4, "score": 87, "comment": "Great experience!", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-05", "userName": "Isabella Garcia", "rating": 5, "score": 91, "comment": "Wonderful!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-06", "userName": "Mason Martinez", "rating": 3, "score": 74, "comment": "Average service.", "location": "New York", "sentiment": "negative"},
    {"date": "2024-06-08", "userName": "Logan Davis", "rating": 5, "score": 94, "comment": "Excellent!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-06-09", "userName": "Jacob Anderson", "rating": 4, "score": 88, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-10", "userName": "Amelia Hernandez", "rating": 3, "score": 72, "comment": "Could be better.", "location": "Houston", "sentiment": "negative"},
    {"date": "2024-06-11", "userName": "William Martinez", "rating": 4, "score": 84, "comment": "Good, but can improve.", "location": "New York", "sentiment": "positive"},
    {"date": "2024-06-12", "userName": "Charlotte Johnson", "rating": 5, "score": 97, "comment": "Amazing!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-06-13", "userName": "Logan Brown", "rating": 3, "score": 75, "comment": "Decent service.", "location": "Chicago", "sentiment": "negative"},
    {"date": "2024-06-14", "userName": "Michael Garcia", "rating": 4, "score": 86, "comment": "Very good.", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-15", "userName": "Sophia Davis", "rating": 5, "score": 93, "comment": "Exceptional service!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-06-16", "userName": "Benjamin Rodriguez", "rating": 3, "score": 70, "comment": "Fair experience.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-06-17", "userName": "Emily Wilson", "rating": 4, "score": 89, "comment": "Great!", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-18", "userName": "William Anderson", "rating": 4, "score": 90, "comment": "Loved it!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-19", "userName": "Olivia Thomas", "rating": 5, "score": 96, "comment": "Fantastic!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-06-20", "userName": "James Wilson", "rating": 3, "score": 73, "comment": "Average.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-06-21", "userName": "Sophia Johnson", "rating": 4, "score": 82, "comment": "Good service.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-22", "userName": "Ethan Brown", "rating": 4, "score": 88, "comment": "Very satisfied!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-23", "userName": "Isabella Garcia", "rating": 5, "score": 92, "comment": "Excellent!", "location": "New York", "sentiment": "positive"},
    {"date": "2024-06-24", "userName": "Mason Martinez", "rating": 3, "score": 77, "comment": "Average experience.", "location": "Los Angeles", "sentiment": "negative"},
    {"date": "2024-06-25", "userName": "Ava Wilson", "rating": 4, "score": 85, "comment": "Very pleased.", "location": "Chicago", "sentiment": "positive"},
    {"date": "2024-06-26", "userName": "Logan Davis", "rating": 5, "score": 98, "comment": "Absolutely fantastic!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-27", "userName": "Jacob Anderson", "rating": 4, "score": 79, "comment": "Good service.", "location": "New York", "sentiment": "positive"},
    {"date": "2024-06-28", "userName": "Sophia Davis", "rating": 5, "score": 95, "comment": "Exceptional!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-06-29", "userName": "Benjamin Rodriguez", "rating": 3, "score": 71, "comment": "Fair.", "location": "New York", "sentiment": "negative"},
    {"date": "2024-06-30", "userName": "Emily Wilson", "rating": 4, "score": 88, "comment": "Would recommend!", "location": "Los Angeles", "sentiment": "positive"},
    {"date": "2024-07-01", "userName": "Olivia Thomas", "rating": 5, "score": 98, "comment": "Absolutely fantastic!", "location": "Houston", "sentiment": "positive"},
    {"date": "2024-07-02", "userName": "James Wilson", "rating": 3, "score": 79, "comment": "Satisfactory.", "location": "New York", "sentiment": "negative"},
    [
        {"date": "2024-07-01", "userName": "John Doe", "rating": 4, "score": 85, "comment": "Great service!", "location": "New York", "sentiment": "positive"},
        {"date": "2024-07-01", "userName": "Jane Smith", "rating": 3, "score": 75, "comment": "It was okay.", "location": "Houston", "sentiment": "neutral"},
        {"date": "2024-07-01", "userName": "Alice Johnson", "rating": 2, "score": 60, "comment": "Not satisfied.", "location": "Los Angeles", "sentiment": "negative"},
        {"date": "2024-07-01", "userName": "Robert Brown", "rating": 5, "score": 95, "comment": "Excellent!", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-01", "userName": "Michael Davis", "rating": 3, "score": 70, "comment": "Average experience.", "location": "New York", "sentiment": "neutral"},
        {"date": "2024-07-01", "userName": "Emily Wilson", "rating": 1, "score": 50, "comment": "Very bad service.", "location": "Houston", "sentiment": "negative"},
        {"date": "2024-07-01", "userName": "Daniel Martinez", "rating": 4, "score": 80, "comment": "Good, but can improve.", "location": "Los Angeles", "sentiment": "positive"},
        {"date": "2024-07-01", "userName": "Sarah Anderson", "rating": 3, "score": 78, "comment": "Not bad.", "location": "Chicago", "sentiment": "neutral"},
        {"date": "2024-07-02", "userName": "David Thomas", "rating": 5, "score": 90, "comment": "Loved it!", "location": "New York", "sentiment": "positive"},
        {"date": "2024-07-02", "userName": "Laura Jackson", "rating": 2, "score": 65, "comment": "Could be better.", "location": "Houston", "sentiment": "negative"},
        {"date": "2024-07-02", "userName": "Mark Wilson", "rating": 4, "score": 85, "comment": "Very good.", "location": "Los Angeles", "sentiment": "positive"},
        {"date": "2024-07-02", "userName": "Emma Brown", "rating": 3, "score": 77, "comment": "It was fine.", "location": "Chicago", "sentiment": "neutral"},
        {"date": "2024-07-02", "userName": "James Garcia", "rating": 1, "score": 55, "comment": "Horrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-02", "userName": "Sophia Hernandez", "rating": 5, "score": 93, "comment": "Absolutely amazing!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-02", "userName": "Alexander Martinez", "rating": 3, "score": 74, "comment": "Just okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-02", "userName": "Olivia Miller", "rating": 4, "score": 82, "comment": "Good service.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "William Davis", "rating": 2, "score": 68, "comment": "Not great.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-03", "userName": "Isabella Rodriguez", "rating": 5, "score": 91, "comment": "Excellent!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "Mason Wilson", "rating": 3, "score": 79, "comment": "Average.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-03", "userName": "Ava Garcia", "rating": 4, "score": 84, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "Ethan Hernandez", "rating": 2, "score": 66, "comment": "Disappointed.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-03", "userName": "Charlotte Smith", "rating": 3, "score": 76, "comment": "It was okay.", "location": "Houston", "sentiment": "neutral"},
        {"date": "2024-07-03", "userName": "Logan Johnson", "rating": 4, "score": 88, "comment": "Would recommend!", "location": "Los Angeles", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "Amelia Brown", "rating": 3, "score": 75, "comment": "Not bad.", "location": "Chicago", "sentiment": "neutral"},
        {"date": "2024-07-04", "userName": "Jacob Garcia", "rating": 5, "score": 94, "comment": "Outstanding!", "location": "New York", "sentiment": "positive"},
        {"date": "2024-07-04", "userName": "Lily Martinez", "rating": 2, "score": 62, "comment": "Bad service.", "location": "Houston", "sentiment": "negative"},
        {"date": "2024-07-04", "userName": "Michael Wilson", "rating": 4, "score": 81, "comment": "Pretty good.", "location": "Los Angeles", "sentiment": "positive"},
        {"date": "2024-07-04", "userName": "Sophia Davis", "rating": 3, "score": 78, "comment": "Not bad.", "location": "Chicago", "sentiment": "neutral"},
        {"date": "2024-07-04", "userName": "Benjamin Rodriguez", "rating": 1, "score": 54, "comment": "Terrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-04", "userName": "Emily Wilson", "rating": 5, "score": 92, "comment": "Amazing!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-04", "userName": "William Anderson", "rating": 3, "score": 77, "comment": "It was okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-04", "userName": "Olivia Thomas", "rating": 4, "score": 86, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "James Wilson", "rating": 2, "score": 67, "comment": "Not good.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-05", "userName": "Sophia Johnson", "rating": 5, "score": 90, "comment": "Fantastic!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "Ethan Brown", "rating": 3, "score": 74, "comment": "Just okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-05", "userName": "Isabella Garcia", "rating": 4, "score": 85, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "Mason Martinez", "rating": 1, "score": 58, "comment": "Very bad.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-05", "userName": "Logan Davis", "rating": 5, "score": 93, "comment": "Loved it!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "Ava Anderson", "rating": 3, "score": 76, "comment": "It was fine.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-05", "userName": "Amelia Miller", "rating": 4, "score": 87, "comment": "Good service.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "Ethan Wilson", "rating": 2, "score": 63, "comment": "Disappointed.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-06", "userName": "Sophia Johnson", "rating": 5, "score": 89, "comment": "Excellent!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "Mason Brown", "rating": 3, "score": 78, "comment": "Average.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-06", "userName": "Isabella Garcia", "rating": 4, "score": 82, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "William Martinez", "rating": 1, "score": 54, "comment": "Horrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-06", "userName": "Charlotte Smith", "rating": 5, "score": 92, "comment": "Outstanding!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "Michael Wilson", "rating": 3, "score": 77, "comment": "It was okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-06", "userName": "Olivia Davis", "rating": 4, "score": 88, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "Jacob Rodriguez", "rating": 2, "score": 65, "comment": "Could be better.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-07", "userName": "Lily Martinez", "rating": 5, "score": 94, "comment": "Fantastic!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "Michael Wilson", "rating": 3, "score": 76, "comment": "It was fine.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-07", "userName": "Sophia Davis", "rating": 4, "score": 83, "comment": "Good service.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "Benjamin Wilson", "rating": 1, "score": 57, "comment": "Terrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-07", "userName": "Emily Johnson", "rating": 5, "score": 91, "comment": "Amazing!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "William Anderson", "rating": 3, "score": 79, "comment": "Just okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-07", "userName": "Olivia Thomas", "rating": 4, "score": 86, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-01", "userName": "James Garcia", "rating": 2, "score": 60, "comment": "Not good.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-01", "userName": "Sophia Rodriguez", "rating": 5, "score": 90, "comment": "Excellent!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-01", "userName": "Mason Martinez", "rating": 3, "score": 75, "comment": "Average.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-01", "userName": "Isabella Brown", "rating": 4, "score": 82, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-02", "userName": "William Wilson", "rating": 1, "score": 58, "comment": "Horrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-02", "userName": "Emily Davis", "rating": 5, "score": 94, "comment": "Outstanding!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-02", "userName": "James Smith", "rating": 3, "score": 77, "comment": "It was okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-02", "userName": "Sophia Anderson", "rating": 4, "score": 88, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "Ethan Wilson", "rating": 2, "score": 66, "comment": "Disappointed.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-03", "userName": "Sophia Johnson", "rating": 5, "score": 89, "comment": "Excellent!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-03", "userName": "Mason Brown", "rating": 3, "score": 78, "comment": "Average.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-03", "userName": "Isabella Garcia", "rating": 4, "score": 82, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-04", "userName": "William Martinez", "rating": 1, "score": 54, "comment": "Horrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-04", "userName": "Charlotte Smith", "rating": 5, "score": 92, "comment": "Outstanding!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-04", "userName": "Michael Wilson", "rating": 3, "score": 77, "comment": "It was okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-04", "userName": "Olivia Davis", "rating": 4, "score": 88, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "Jacob Rodriguez", "rating": 2, "score": 65, "comment": "Could be better.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-05", "userName": "Lily Martinez", "rating": 5, "score": 94, "comment": "Fantastic!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-05", "userName": "Michael Wilson", "rating": 3, "score": 76, "comment": "It was fine.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-05", "userName": "Sophia Davis", "rating": 4, "score": 83, "comment": "Good service.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "Benjamin Wilson", "rating": 1, "score": 57, "comment": "Terrible experience.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-06", "userName": "Emily Johnson", "rating": 5, "score": 91, "comment": "Amazing!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-06", "userName": "William Anderson", "rating": 3, "score": 79, "comment": "Just okay.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-06", "userName": "Olivia Thomas", "rating": 4, "score": 86, "comment": "Very satisfied.", "location": "Chicago", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "James Garcia", "rating": 2, "score": 60, "comment": "Not good.", "location": "New York", "sentiment": "negative"},
        {"date": "2024-07-07", "userName": "Sophia Rodriguez", "rating": 5, "score": 90, "comment": "Excellent!", "location": "Houston", "sentiment": "positive"},
        {"date": "2024-07-07", "userName": "Mason Martinez", "rating": 3, "score": 75, "comment": "Average.", "location": "Los Angeles", "sentiment": "neutral"},
        {"date": "2024-07-07", "userName": "Isabella Brown", "rating": 4, "score": 82, "comment": "Very good.", "location": "Chicago", "sentiment": "positive"}
    ]
    
];
export default data;
